# Generated by Django 4.1.7 on 2023-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=250)),
                ('rate', models.PositiveIntegerField()),
            ],
        ),
    ]
